@startuml e-commerce

class Product {
    - name: String
    - category: String
    - description: String
    - value: Decimal
    - storage: Integer
    - data_created: DateTime
    - data_updated: DateTime
}

class User {
    - username: String
    - first_name: String
    - last_name: String
    - cpf: String
    - email: String
    - password: String
}

class Cart {
    - user: User
    - data_updated: DateTime
}

class ItemCart {
    - cart: Cart
    - product: Product
    - quantity: Integer
}

User "1" -- "1" Cart : owns
Cart "1" -- "0..*" ItemCart : contains
Product "1" -- "0..*" ItemCart : included_in

@enduml
