# Generated by Django 5.1.3 on 2024-11-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenscart',
            old_name='quantidade',
            new_name='quantity',
        ),
    ]
