# Generated by Django 5.1.4 on 2024-12-28 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_carts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscart',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
